function apply_yaxis_style(ax, ystyle)
if nargin<2 || ~ishghandle(ax), return; end
set(ax,'YDir','normal', ...
       'YLim', ystyle.YLim, ...
       'YTick', ystyle.YTick, ...
       'YTickLabel', ystyle.YTickLabel, ...
       'YLimMode','manual','CLimMode','auto', ...
       'XTickMode','auto','YTickMode','manual');
ylabel(ax, ystyle.YLabel, 'Interpreter','none');
end
