function handles = binarize_regr(handles)

m = str2double(get(handles.txtBinarize,'String')); 
max_pred = max(handles.curRegr.pred);
min_pred = min(handles.curRegr.pred);
if isempty(m)
    errordlg('Enter numeric threshold')    
elseif m < min_pred || m > max_pred
    errordlg(sprintf('Threshold out of target range [%g %g]',min_pred,max_pred));
end
axes(handles.axes1)
% Print horizontal binarization line in axes1
% If the lines already exist and are graphics objects, just reposition
% Get current axis limits
xl = get(handles.axes1,'XLim');
yl = get(handles.axes1,'YLim');

% Check if the line + label already exist
hasHLine = isfield(handles,'binarize_hline') && isgraphics(handles.binarize_hline,'line');
hasVLine = isfield(handles,'binarize_vline') && isgraphics(handles.binarize_vline,'line');
hasLabel = isfield(handles,'binarize_hline_text') && isgraphics(handles.binarize_hline_text,'text');

if hasHLine && hasVLine
    % Just update endpoints
    set(handles.binarize_hline, ...
        'XData', xl, ...
        'YData', [m m]);
    set(handles.binarize_vline, ...
        'XData', [m m], ...
        'YData', yl);
else
    % First‐time creation of the lines
    handles.binarize_hline = line( ...
        xl, [m m], ...
        'Color','r', ...
        'LineWidth',1.25, ...
        'Tag','binarize_hline' ...
    );
    handles.binarize_vline = line( ...
        [m m], yl, ...
        'Color','r', ...
        'LineWidth',1.25, ...
        'Tag','binarize_vline' ...
    );
end

% Delete legend entries for binarization lines.
fx = contains(handles.axes1.Legend.String,{'data1','data2'});
handles.axes1.Legend.String(fx)=[];

% Now update or create the text label at the right end of the h-line
txtX = xl(2)-0.005;  % place at right axis limit
txtY = m;
if hasLabel
    set(handles.binarize_hline_text, ...
        'Position', [txtX, txtY], ...
        'String',   'Binarization threshold');
else
    handles.binarize_hline_text = text( ...
        txtX, txtY, ...
        'Binarization threshold', ...
        'Color','r', ...
        'HorizontalAlignment','right', ...
        'VerticalAlignment','bottom', ...
        'FontWeight','normal', ...    % HTML not needed here
        'Tag','binarize_hline_text' ...
    );
end

% Display ROC
[handles.hroc, handles.hroc_random] = display_roc(handles, handles.curRegr.b_label, handles.curRegr.b_pred);

% Display pie charts
[handles.h1pie, handles.h2pie] = display_piecharts(handles);
