% ==========================================================================
function opt = nk_matLearn_getopts_config(opt, act, algo, param, framework)

if ~exist('param','var'), param = []; end

switch act
    
    case {'get_learners','get_sublearners'}
        
        opt.desc    = sprintf('Select %s algorithm from the matLearn library',framework);
        opt.name    = 'algo';
        opt.def     = 1;
        
        switch act
            case 'get_learners'
                switch framework
                    case 'regression'
                            opt.format  = ['Absolute Loss Linear Regression|' ...
                                                'Squared Loss Linear Regression|' ...
                                                'Least Squares Regression|', ...
                                                'Student''s Loss Regression|', ...
                                                'K-Nearest Neighbour Regression|', ...
                                                'Naive Bayes Squared Loss Linear Regression|', ...
                                                'Multi-layer Perceptron with tanh Activation Function|', ...
                                                'Local Regression|', ...
                                                'Huberized regression|', ...
                                                'Mean regression|', ...
                                                'Stump regression|', ...
                                                'GAM model providing either smooth cubic splines, regression of degree, or linear regressions|', ...
                                                'Type-2 MLE for linear regression using Mackay''s implementation'];

                            opt.sel     = {'L1','L2','leastSquares','student','NW','NB','MLP','local','Huber','mean','stump','GAM','ARD'};

                    case 'binaryclass'
                            opt.format  = [ 'Boosting Algorithm (AdaBoost, LogitBoost)|' ...
                                            'Decision Stump Classifier|', ...
                                            'Broken Stump Classifier|', ...
                                            'Huberized hinge-loss SVM|', ...
                                            'L2-SVM|', ...
                                            'Smooth SVM with squared hinge loss|', ...
                                            'Logistic regression with L2-regularization|', ...
                                            'Elastic-net logistic regression|', ...
                                            'Random Forest|', ...
                                            'Multi-layer Perceptron|', ...
                                            'GLM with extreme link|', ...
                                            'GLM with Cauchit link|', ...
                                            'GLM optimizing the exponential loss' ];
                            opt.sel     = {'boosting','stump','brokenStump','HSVM', 'SVM', 'SSVM', 'logistic', 'elastic_net', 'randomForest', 'MLP', 'extreme', 'Cauchit','exponential'};
                end
                
                if ~isempty(param) && isfield(param,'algo')
                    f = find(strcmp(opt.sel,char(param.algo)));
                    if ~isempty(f), opt.def = f; end
                end
                
            case 'get_sublearners'
                 switch framework
                    case 'regression'
                            opt.format  = ['Naive Bayes Squared Loss Linear Regression|', ...
                                            'Mean regression|', ...
                                            'Stmup regression'];
                            opt.sel     = {'NB','mean','stump'};

                    case 'binaryclass'
                            opt.format  = [ 'Decision Stump Classifier|', ...
                                            'Broken Stump Classifier|', ...
                                            'SVM|', ...
                                            'Logistic regression with L2-regularization|', ...
                                            'GLM with extreme link|', ...
                                            'GLM with Cauchit link|', ...
                                            'GLM optimizing the exponential loss'];
                            opt.sel     = {'stump','brokenStump','SVM', 'logistic', 'extreme', 'Cauchit', 'exponential'};
                 end
                
                 if ~isempty(param) && isfield(param,'algo')
                    f = find(strcmp(opt.sel,char(param.algo)));
                    if ~isempty(f), opt.def = f; end
                 end
        end
        
    case 'get_kernel_func'
        
        switch algo
            case 'ROBSVM'
                opt.desc    = sprintf('Select kernel function of %s', algo);
                opt.format  = 'Linear|Polynomial|RBF';
                opt.sel     = {'-t 0','-t 1','-t 2'};
                opt.def     =  1;
                opt.name    = 'kernelFunc';
            otherwise
                opt.desc    = sprintf('Select kernel function for %s', algo);
                opt.format  = 'Linear|Polynomial|RBF';
                opt.sel     = {'@ml_kernel_gram','@ml_kernel_poly','@ml_kernel_rbf'};
                opt.def     =  1;
                opt.name    = 'kernelFunc';
        end
        
    case 'get_kernel_params'

        switch algo
            case '@ml_kernel_rbf'
                opt.desc    = 'Define sigma of RBF kernel';
                opt.format  = 'e';
                opt.sel     = [];
                opt.def     = 1;
                opt.name    = 'sigma';
            case '@ml_kernel_poly'
                opt.desc    = {'Add bias to the polynomial basis', 'Define degree of polynomial basis'};
                opt.format  = {'yes|no','i'};
                opt.sel     = {[1 0],[]};
                opt.def     = {1,2};
                opt.name    = {'bias','order'};
            case '-t 1'
                opt.desc    = {'Define coefficient of polynomial basis', 'Define degree of polynomial basis'};
                opt.format  = {'i','i'};
                opt.sel     = {[],[]};
                opt.def     = {0,2};
                opt.name    = {'coef0','degree'};
            case '-t 2'
                opt.desc    = 'Define sigma of RBF kernel';
                opt.format  = 'e';
                opt.sel     = [];
                opt.def     = 2.^(-10:2:0);
                opt.name    = 'gamma';
            otherwise
                opt = [];
        end
        opt.algo = algo;
                
    case 'get_learner_params'
        
        switch algo
            case {'stump', 'brokenStump', 'mean'}
                opt = [];
            case {'leastSquares'}
                opt.desc = {'Define L2-lambda parameter range'};
                opt.format = {'e'};
                opt.sel = {[]};
                opt.def = {0};
                opt.name = {'lambdaL2'};
            case {'L1','L2','NB','SVM','exponential'}
                opt.desc = {'Add bias','Define L2-lambda parameter range'};
                opt.format = {'yes|no','e'};
                opt.sel = {[1 0],[]};
                opt.def = {1,0};
                opt.name = {'addBias','lambdaL2'};
            case {'elastic_net'}
                opt.desc = {'Add bias','Define L1-lambda parameter range', 'Define L2-lambda parameter range'};
                opt.format = {'yes|no','e','e'};
                opt.sel = {[1 0],[],[]};
                opt.def = {1,0,0};
                opt.name = {'addBias','lambdaL1','lambdaL2'};
            case 'student'
                opt.desc = {'Add bias','Define L2-lambda parameter range','Define polynomial coefficient range'};
                opt.format = {'yes|no','e','e'};
                opt.sel = {[1 0],[],[]};
                opt.def  = {1, 0, 1};
                opt.name = {'addBias','lambdaL2','poly'};
            case 'GLMNET'
                opt.desc = {'Define mixing factor (alpha) range ( 0 =ridge <-> 1 =lasso )', ...
                            'Define minimum lambda range (e.g. if N_cases>N_feats: 0.0001, otherwise 0.01)', ...
                            'Define number of lambda optimization steps', ...
                            'Define maximum number(s) of variables in the model', ...
                            'Standardize input matrix to unit variance prior to training the elastic net'};
                opt.format = {'e','e','i','i', 'yes|no'};
                opt.sel = {[],[],[],[],[1 0]};
                opt.def  = {0.5, 0.001, 100, Inf, 0};
                opt.name = {'alpha','lambda_min','nlambda','dfmax','standardize'};
            case 'GRDBST'
                opt.desc = {'Define maximum number of boosting iterations', ...
                    'Select type of loss (exponential/deviance for classification, squared/absolute/huber/quantile for regression)', ...
                    'Define learning rate (0<->1)', ...                            
                    'Define subsampling factor (0<->1)', ...
                    'Define maximum tree depth'};
                % possible other parameters:
                % min_samples_leaf,
                % min_weight_fraction_leaf,
                % min_impurity_decrease, %criterion (to measure the quality of a split),
                % init,
                % random_state,
                % max_features,
                % alpha,
                % max_leaf_nodes,
                % warm_start,
                % validation_fraction,
                % n_iter_no_change,
                % tol,
                % ccp_alpha

                switch framework
                    case 'classification'
                        opt.format = {'i', ...
                            'log_loss|exponential', ... %LATER: add alpha parameter to define alpha-quantile for huber and quantile; for now sklearn GradientBoostingRegressor default = 0.9
                            'e', ...
                            'e', ...
                            'e'};
                        opt.sel    = {[], ...
                            {'log_loss','exponential'}, ...
                            [],...
                            [],...
                            []};
                        opt.def  = {100, 'log_loss', 0.1, 1.0, 3};
                        
                    case 'regression'
                        opt.format = {'i', ...
                            'squared_error | absolute_error | huber | quantile', ... %LATER: add alpha parameter to define alpha-quantile for huber and quantile; for now sklearn GradientBoostingRegressor default = 0.9
                            'e', ...
                            'e', ...
                            'e'};
                        opt.sel    = {[], ...
                            {'squared_error','absolute_error', 'huber', 'quantile'}, ...
                            [],...
                            [],...
                            []};
                        opt.def  = {100, 'squared_error', 0.1, 1.0, 3};
                end

                opt.name = {'maxIters','loss','learningRate','subsamplingFactor','maxTreeDepth'};

            case 'MLPERC'

                opt.desc = {'Define MLP structures: hidden layers (length of row) and sizes (values)', ...
                            'Select activation function', ...
                            'Select solver method', ...
                            'Define alpha parameter (L2 reg. coefficient)', ...
                            'Select batch size', ...
                            'Select learning rate strategy', ...
                            'Define initial learning rate', ...
                            'Define power parameter for learning rate decay', ...
                            'Set maximum number of iterations', ...
                            'Set random seed', ...
                            'Define tolerance for optimization', ...
                            'Use warm start', ...
                            'Set momentum parameter', ...
                            'Use Nesterov''s momentum', ...
                            'Set early stopping', ...
                            'Define validation data fraction', ...
                            'Define beta_1 parameter', ...
                            'Define beta_2 parameter', ...
                            'Define epsilon parameter for numerical stability', ...
                            'Set number of iterations with no improvement before stopping', ...
                            'Set maximum function evaluations'};

                opt.sel = {[], ...
                            {'identity', 'logistic', 'tanh', 'relu'}, ...
                            {'lbfgs', 'sgd', 'adam'}, ...
                            [], ...
                            {'auto'}, ...
                            {'constant', 'invscaling', 'adaptive'}, ...
                            [], ...
                            [], ...
                            [], ...
                            [], ...
                            [], ...
                            [1 0], ...
                            [], ...
                            [1 0], ...
                            [1 0], ...
                            [], ...
                            [], ...
                            [], ...
                            [], ...
                            [], ...
                            []};

                opt.def = {[100, 100], ...
                            'relu', ...
                            'adam', ...
                            0.0001, ...
                            200, ...
                            'constant', ...
                            0.001, ...
                            0.5, ...
                            1000, ...
                            45, ...
                            1e-4, ...
                            0, ...
                            0.9, ...
                            1, ...
                            0, ...
                            0.1, ...
                            0.9, ...
                            0.999, ...
                            1e-8, ...
                            10, ...
                            15000};


                opt.format = {'mlp_struct_def', ...
                            'identity|logistic|tanh|relu', ...
                            'lbfgs|sgd|adam', ...
                            'e', ...
                            'i', ...
                            'constant|invscaling|adaptive', ...
                            'e', ...
                            'e', ...
                            'i', ...
                            'i', ...
                            'e', ...
                            'yes|no', ...
                            'e', ...
                            'yes|no', ...
                            'yes|no', ...
                            'e', ...
                            'e', ...
                            'e', ...
                            'e', ...
                            'i', ...
                            'i'};

                opt.name = {'MLPERC_hidden_layer_sizes', ...
                        'MLPERC_activation', ...
                        'MLPERC_solver', ...
                        'MLPERC_alpha', ...
                        'MLPERC_batch_size', ...
                        'MLPERC_learning_rate', ...
                        'MLPERC_learning_rate_init', ...
                        'MLPERC_power_t', ...
                        'MLPERC_max_iter', ...
                        'MLPERC_random_state', ...
                        'MLPERC_tol', ...
                        'MLPERC_warm_start', ...
                        'MLPERC_momentum', ...
                        'MLPERC_nesterovs_momentum', ...
                        'MLPERC_early_stopping', ...
                        'MLPERC_validation_fraction', ...
                        'MLPERC_beta_1', ...
                        'MLPERC_beta_2', ...
                        'MLPERC_epsilon', ...
                        'MLPERC_n_iter_no_change', ...
                        'MLPERC_max_fun'};

            case 'BAYLIN'

                opt.desc = { ...
                    'Select estimator (BayesianRidge or ARDRegression)', ...
                    'Set maximum number of iterations (n_iter)', ...
                    'Set convergence tolerance (tol)', ...
                    'Gamma prior alpha_1 (precision of the noise prior)', ...
                    'Gamma prior alpha_2 (precision of the noise prior)', ...
                    'Gamma prior lambda_1 (weights prior)', ...
                    'Gamma prior lambda_2 (weights prior)', ...
                    'Fit intercept', ...
                    'Compute score during training', ...
                    'ARD threshold_lambda (ignored for BayesianRidge)' ...
                };
            
                opt.sel = { ...
                    {'BayesianRidge','ARDRegression'}, ...  % estimator
                    [], ...                                 % n_iter
                    [], ...                                 % tol
                    [], ...                                 % alpha_1
                    [], ...                                 % alpha_2
                    [], ...                                 % lambda_1
                    [], ...                                 % lambda_2
                    [1 0], ...                              % fit_intercept
                    [1 0], ...                              % compute_score
                    [] ...                                  % threshold_lambda (ARD only)
                };
            
                opt.def = { ...
                    'BayesianRidge', ...    % estimator
                    300, ...                % n_iter
                    1e-3, ...               % tol
                    1e-6, ...               % alpha_1
                    1e-6, ...               % alpha_2
                    1e-6, ...               % lambda_1
                    1e-6, ...               % lambda_2
                    1, ...                  % fit_intercept
                    0, ...                  % compute_score
                    1e4 ...                 % threshold_lambda (ARD only)
                };
            
                opt.format = { ...
                    'BayesianRidge|ARDRegression', ...  % estimator
                    'i', ...                             % n_iter
                    'e', ...                             % tol
                    'e', ...                             % alpha_1
                    'e', ...                             % alpha_2
                    'e', ...                             % lambda_1
                    'e', ...                             % lambda_2
                    'yes|no', ...                        % fit_intercept
                    'yes|no', ...                        % compute_score
                    'e' ...                              % threshold_lambda
                };
            
                opt.name = { ...
                    'BAYLIN_estimator', ...
                    'BAYLIN_n_iter', ...
                    'BAYLIN_tol', ...
                    'BAYLIN_alpha_1', ...
                    'BAYLIN_alpha_2', ...
                    'BAYLIN_lambda_1', ...
                    'BAYLIN_lambda_2', ...
                    'BAYLIN_fit_intercept', ...
                    'BAYLIN_compute_score', ...
                    'BAYLIN_threshold_lambda' ...
                };

            case 'TFDEEP'
                opt.desc = {'Define SeqNN structures: hidden layers (length of row) and sizes (values)', ...
                            'Select activation function', ...
                            'Select solver method', ... 
                            'Define alpha parameter (L2 reg. coefficient)', ...
                            'Select batch size', ...
                            'Define initial learning rate', ...
                            'Set maximum number of iterations', ... 
                            'Set random seed', ...
                            'Loss class weighting', ... 
                            'Early stopping', ... 
                            'Patience', ...
                            'Select training loss function', ...
                            'Internal validation', ...
                            'Select validation fraction', ...
                            'Predefined models from files (leave none if using parameters above)', ...
                            };

                opt.sel = {[], ...
                            {'identity', 'sigmoid', 'tanh', 'relu', 'linear', 'softmax'}, ...
                            {'sgd', 'adam', 'adagrad'}, ...
                            [], ...
                            [], ...
                            [], ...
                            [], ...
                            [], ...
                            [1 0], ...
                            [1 0], ...
                            [], ...
                            {}, ... %Edited below.
                            [1 0], ...
                            [], ...
                            []};

                opt.def = {[100, 100], ...
                            'relu', ...
                            'adam', ...
                            0.0001, ...
                            200, ...
                            0.001, ...
                            10, ...
                            45, ...
                            0, ...
                            1, ...
                            5, ...
                            '', ...
                            1, ...
                            0.1, ...
                            'none'};


                opt.format = {'mlp_struct_def', ...
                            'identity|sigmoid|tanh|relu|linear|softmax', ...
                            'sgd|adam|adagrad', ...
                            'e', ...
                            'i', ...
                            'e', ...
                            'i', ...
                            'i', ...
                            'yes|no', ...
                            'yes|no', ...
                            'i', ...
                            '', ...
                            'yes|no', ...
                            'e', ...
                            'tf_struct_file_def'};

                opt.name = {'TFDEEP_hidden_layer_sizes', ...
                        'TFDEEP_activation', ...
                        'TFDEEP_solver', ...
                        'TFDEEP_alpha', ...
                        'TFDEEP_batch_size', ...
                        'TFDEEP_learning_rate_init', ...
                        'TFDEEP_max_iter', ...
                        'TFDEEP_random_state', ...
                        'TFDEEP_class_weighting',...
                        'TFDEEP_early_stopping', ...
                        'TFDEEP_patience', ...
                        'TFDEEP_loss', ...
                        'TFDEEP_validation', ...
                        'TFDEEP_validation_fraction', ...
                        'TFDEEP_files' ...
                        };

                %Configure loss depending on framework. 
                switch framework
                    case 'classification'
                        opt.sel{12} = {'categorical_crossentropy', ...
                                       'kl_divergence', ...
                                       'categorical_hinge', ...
                                       'performance_criterion' ...
                                       };
                        opt.def{12} = 'categorical_crossentropy';

                        opt.format{12} = 'categorical_crossentropy|kl_divergence|categorical_hinge|performance_criterion (optimise NeuroMiner metric)';

                    case 'regression'
                        opt.sel{12} = { ...
                            'mean_squared_error', ...       
                            'mean_absolute_error', ...       
                            'mean_absolute_percentage_error', ...  
                            'huber', ...                    
                            'log_cosh', ...                  
                            'cosine_similarity', ...         
                            'performance_criterion' ...      
                        };
                        opt.def{12} = 'mean_squared_error';
                        opt.format{12} = 'mean_squared_error|mean_absolute_error|mean_absolute_percentage_error|huber|log_cosh|cosine_similarity|performance_criterion (optimize NeuroMiner metric)';
                 end

            case 'ROBSVM'
                switch framework
                    case 'binaryclass'
                        learn_desc = 'C-SVC|nu-SVC'; learn_sel = {'-s 0', '-s 1'};

                    case 'regression'
                        learn_desc = 'epsilon-SVR|nu-SVR'; learn_sel = {'-s 3', '-s 4'}; 
                 end
                learn_def = learn_sel{1};
                opt.desc    = {'Define number of training data splits', ...
                                'Select winsorization threshold(s)', ...
                                'Select LIBSVM learner', ...
                                'Define cost parameters (only needed for C-SVC, epsilon-SVR, nu-SVR)', ...
                                'Define nu parameters (only needed for nu-SVC and nu-SVR)', ...
                                'Define epsilon parameters (only needed for epsilon-SVR)', ...
                                'Select kernel type', ...
                                'Define the kernel parameters'};
                opt.format  = {'i','i',learn_desc, 'e','e','e','kernel_func_selector','kernel_params_selector'};
                opt.sel     = {[],[],learn_sel, [], [], [], [], []};
                opt.def     = {3, 4, learn_def, 1, 0.5, 0.1, [], []};
                opt.name    = {'nsplit','wins','learner','cost','nu','epsilon','kernelFunc','kernelOptions'};
            case 'DECTRE'
                opt.desc    = {'Define parameter opimization method', ...
                                'Select type of optimization', ...
                                'Select LIBSVM learner', ...
                                'Define cost parameters (only needed for C-SVC, epsilon-SVR, nu-SVR)', ...
                                'Define nu parameters (only needed for nu-SVC and nu-SVR)', ...
                                'Define epsilon parameters (only needed for epsilon-SVR)', ...
                                'Select kernel type', ...
                                'Define the kernel parameters'};
                opt.format  = {'Cross-validation|Hyperparameter optimization','i','e','e','e'};
                opt.sel     = {{'manual','auto'},[],[], [], [] };
                opt.def     = {1, 4, 1, 0.5, 0.1 };
                opt.name    = {'nsplit','wins','learner','cost','nu','epsilon'}; 
            case 'ELASVM'
                opt.desc = {'Define t range (L1-norm budget)', ...
                            'Define lambda range (-c 1/(2*lambda)', ...
                            'Define LIBLINEAR solver (-s param)', ...
                            'Define solver tolerance (-e param)'};
                opt.format = {'e', 'e', 'L2-regularized L2-loss support vector classification (primal)|L2-regularized L2-loss support vector classification (dual)','e'};
                opt.sel    = {[], [], [2 1],[], []};
                opt.def  = {[1 2 4 8 16], [0.0625 0.125 0.25 0.5 1 2 4], 2, 0.01};
                opt.name = {'L1-budget','lambda','Solver','epsilon'};
            case 'NW'
                %uses only kernel params
                opt.def  = [];
                opt.name = [];
            case 'MLP'
                switch framework
                    case 'binaryclass'
                        opt.desc = {'Define vector of the size of each hidden layer in the multi-layer perceptron'};
                        opt.format = {'e'};
                        opt.sel = {[]};
                        opt.def  = {[3,3,3]};
                        opt.name = {'nHidden'};
                    case 'regression'
                        opt.desc = {'Define sizes of hidden layers in the multi-layer perceptron','Define active function'};
                        opt.format = {'e','s'};
                        opt.sel = {[],'tanh'};
                        opt.def  = {[3 6 9],'tanh'};
                        opt.name = {'nHidden','activFunc'};
                end    
            case 'local'
                opt.desc = {'Select submodel learner','Define submodel options',};
                opt.format = {'model_selector','options_selector','i','s'};
                opt.sel = {[], [], [], []};
                opt.def = {[], [], 1, 1};
                opt.name = {'subModel','subOptions','k','weightingFunc'};
            case 'Huber'
                opt.desc = {'Add bias','Define L2-lambda parameter range','Define epsilon parameter range'};
                opt.format = {'yes|no','e','e'};
                opt.sel = {[1 0],[],[]};
                opt.def  = {1, 0, 1};
                opt.name = {'addBias','lambdaL2','epsilon'};
            case 'ARD'
                opt.desc = {'Add bias','Define sigma2 parameter'};
                opt.format = {'yes|no','e'};
                opt.sel = {[1 0],[]};
                opt.def = {1,0};
                opt.name = {'addBias','sigma2'};
            case 'GAM'
                opt.desc = {'Define number of iterations', ...
                            'Define function used to determine f''s', ...
                            'Define highest exponent degree for polynomial subFunc', ...
                            'Define smoothness of smooth cubic splines subFunc (0 = linear regression ... 1 = unsmoothed cublic splines)', ...
                            'Define max number of iteratons for backfitting'};
                opt.format = {'e', ...
                            'smooth cubic splines|polynomial regression|linear regresion', ...
                            'e',...
                            'e',...
                            'e'};
                opt.sel = {[],{'sp1','rg','lin'},[],[],[]};
                opt.def = {500,1,2,0.8,500};
                opt.name = {'numIter','subFunc','deg','smoothing','maxIter'};
            case 'boosting'
                opt.desc = {'Select the boosting algorithm', ...
                            'Define the number of weak learners to train', ...
                            'Select the base classifier to use', ...
                            'Define the parameters of the base classifier'};
                opt.format = {'ada|logit', 'e', 'model_selector','options_selector'};
                opt.sel    = {{'ada','logit'},[],[],[]};
                opt.def    = {1,50,[],[]};
                opt.name = {'booster','nBoosts','subModel','subOptions'};
            case 'HSVM'
                opt.desc = {'Add bias', ...
                            'Define L1-lambda parameter range', ...
                            'Define L2-lambda parameter range', ...
                            'Define epsilon parameter range', ...
                            'Enable kernelization', ...
                            'Select the kernel function', ...
                            'Define the kernel parameters'};
                opt.format = {'yes|no','e','e','e','yes|no','kernel_func_selector','kernel_params_selector'};
                opt.sel = {[1 0],[],[],[], [1 0],[],[]};
                opt.def  = {1, 0, 0, 0.5, 0,[],[]};
                opt.name = {'addBias','lambdaL1','lambdaL2','epsilon','kernel','kernelFunc','kernelOptions'};
            case 'SSVM'
                opt.desc = {'Add bias', ...
                            'Define L2-lambda parameter range', ...
                            'Enable kernelization', ...
                            'Select the kernel function', ...
                            'Define the kernel parameters'};
                opt.format = {'yes|no','e','yes|no','kernel_func_selector','kernel_params_selector'};
                opt.sel = {[1 0],[],[1 0],[],[]};
                opt.def  = {1, 1, 0,[],[]};
                opt.name = {'addBias','lambdaL2','kernel','kernelFunc','kernelOptions'};
            case {'extreme','Cauchit'}
                opt.desc = {'Choose distribution (binomial for classification)', ...
                            'Define threshold'};
                opt.format = {'binomial|poisson|gamma|inverse gaussion|normal','e'};
                opt.sel = {{'binomial','poisson','gamma','inverse gaussian', 'normal'},[]};   
                opt.def  = {1, 0.5};
                opt.name = {'dist','thresh'};             
            case 'randomForest'
                opt.desc = {'Choose number of models', ...
                            'Define size of bootstrap sample (max = 1: full training sample)', ...
                            'Define minimum leaf size (the minimum number of training data in leaf nodes)', ...
                            'Choose maximum decision tree depth', ...
                            'Define number of features the each decision tree will consider (max = 1: full feature space)'};
                opt.format = {'e','e','e','e','e'};
                opt.sel = {[],[],[],[],[]};
                opt.def = {10, 0.7, 3, 8, 0.75};
                opt.name = {'nModels','nSample','minLeafSize','maxDepth','maxFeatures'};
        end
        % Overwrite defaults if pre-existing param is available
        if ~isempty(param) && isfield(param,'Params') && ~isempty(param.Params) && ~isempty(opt)
            for i=1:numel(opt.name)
                for j=1:numel(param.Params)
                    if strcmp(param.Params(j).name, opt.name{i})
                        opt.def{i} = nk_matLearn_FindDefInParam_config(opt.format{i}, opt.name{i}, opt.def{i}, opt.sel{i}, param.Params(j));
                    end
                end
            end
        end
        
end